[[connections]]
name               = "snowflake"
account            = "${SNOWFLAKE_ACCOUNT}"
user               = "${SNOWFLAKE_USER}"
private_key_file   = "key.pem"
private_key_file_pwd = "${SNOWFLAKE_PRIVATE_KEY_PASSPHRASE}"
authenticator      = "snowflake_jwt"
role               = "${SNOWFLAKE_ROLE}"
warehouse          = "${SNOWFLAKE_WAREHOUSE}"
database           = "${SNOWFLAKE_DATABASE}"
```
