CREATE OR REPLACE VIEW DEVOPS.HR.EMPLOYEE_DETAILS AS
SELECT
    EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME,
    DEPARTMENT,
    HIRE_DATE,
    CONCAT(FIRST_NAME, ' ', LAST_NAME) AS FULL_NAME
FROM DEVOPS.HR.EMPLOYEES;
