name: Manual Cherry-Pick & PR

on:
  workflow_dispatch:
    inputs:
      commit_hashes:
        description: 'Comma-separated commit hashes to cherry-pick'
        required: true
      source_branch:
        description: 'Source branch (e.g., dev)'
        required: true
        default: 'dev'
      target_branch:
        description: 'Target branch (e.g., QA)'
        required: true
        default: 'QA'
      pr_base_branch:
        description: 'PR base branch (e.g., release)'
        required: true
        default: 'release'

jobs:
  cherry_pick:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Checkout target branch
        run: git checkout ${{ github.event.inputs.target_branch }}

      - name: Cherry-pick commits
        run: |
          for hash in $(echo "${{ github.event.inputs.commit_hashes }}" | tr ',' '\n'); do
            git cherry-pick $hash || exit 1
          done

      - name: Push cherry-pick changes
        run: git push origin ${{ github.event.inputs.target_branch }}

      - name: Create PR using CLI
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          gh pr create \
            --base ${{ github.event.inputs.pr_base_branch }} \
            --head ${{ github.event.inputs.target_branch }} \
            --title "Cherry-pick to ${{ github.event.inputs.target_branch }}" \
            --body "Cherry-picked: ${{ github.event.inputs.commit_hashes }}"
