name: Selective Cherry-Pick PR

on:
  workflow_dispatch:
    inputs:
      source_branch:
        description: 'Branch to pick commits from'
        required: true
        default: 'dev'
      target_branch:
        description: 'Branch to merge into'
        required: true
        default: 'release'
      commits:
        description: 'Comma-separated list of commit SHAs to cherry-pick'
        required: true
      pr_branch_prefix:
        description: 'Prefix for the temporary PR branch'
        required: false
        default: 'selective-pr'

jobs:
  selective_pr:
    name: Cherry-pick & Create PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # fetch all history for cherry-picks and other branches

      - name: Prepare branches and temp PR branch
        run: |
          # Fetch both source and target branches
          git fetch origin ${{ github.event.inputs.source_branch }}:${{ github.event.inputs.source_branch }}
          git fetch origin ${{ github.event.inputs.target_branch }}:${{ github.event.inputs.target_branch }}
          
          # Create a new branch from target
          TIMESTAMP=$(date +"%Y%m%d%H%M%S")
          PR_BRANCH="${{ github.event.inputs.pr_branch_prefix }}-${TIMESTAMP}"
          git checkout -b $PR_BRANCH origin/${{ github.event.inputs.target_branch }}
          echo "PR_BRANCH=$PR_BRANCH" >> $GITHUB_ENV

      - name: Cherry-pick commits from source
        run: |
          IFS=',' read -ra SHAS <<< "${{ github.event.inputs.commits }}"
          for sha in "${SHAS[@]}"; do
            git cherry-pick $sha || exit 1
          done

      - name: Push PR branch
        run: |
          git push origin $PR_BRANCH

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ${{ github.event.inputs.target_branch }}
          head: ${{ env.PR_BRANCH }}
          title: 'Selective PR: ${{ github.event.inputs.commits }}'
          body: |
            Cherry-picked commits from `${{ github.event.inputs.source_branch }}` into this PR:
            ```
            ${{ github.event.inputs.commits }}
            ```
