name: SQLFluff Lint

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'snowflake/**/*.sql'

jobs:
  lint-sql:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install SQLFluff
        run: pip install sqlfluff

      - name: Find changed .sql files in /snowflake
        run: |
          git fetch origin ${{ github.base_ref }}
          git diff --name-only origin/${{ github.base_ref }}...${{ github.sha }} | grep '^snowflake/.*\.sql$' > sqlfiles.txt || true

      - name: Lint changed SQL files
        run: |
          if [[ -s sqlfiles.txt ]]; then
            echo "Linting these SQL files:"
            cat sqlfiles.txt
            xargs -a sqlfiles.txt sqlfluff lint --dialect snowflake
          else
            echo "No changed SQL files under /snowflake"
          fi
